[package]
edition = "2021"
name = "vetovoima"
version = "0.1.0"

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1

[profile.release]
codegen-units = 1
lto = true

[features]
default = [
  "bevy/bevy_winit",
  "bevy/render",
  "bevy/png",
  "bevy/x11",
  "bevy_kira_audio/ogg",
]

dev = [
  "bevy/dynamic",
]

[dependencies]
bevy = "0.7"
bevy-rust-arcade = "0.1.0"
bevy_kira_audio = "0.10.0"
bevy_prototype_lyon = "0.5"
bevy_rapier2d = {version = "0.15.0", features = ["simd-stable", "debug-render"]}
rand = "0.8.5"
rand_distr = "0.4.3"
